name: Firebase CI

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'android or ios'
        required: true
        default: 'android'
        type: choice
        options:
        - android
        - ios

jobs:
  build:

    if ${{ inputs.environment }} == 'android'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g npm
    - name: npm install, build and test
      run: |
        npm install  --prefix my-app
        npm run build  --prefix my-app
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: my-app/build
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: my-app/build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
